import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



export default function Home({todos}) {
  console.log(todos)
  return (
    <div className={styles.container}>
      <Head>
        <title>SSR demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{
  todos?.length===0 ? (
<div>Loading...</div>
  ):(
    todos?.map(todo=>(
     
        <div key={todo.id}>
          <p>
            {todo.id}: {todo.title}
          </p>
          
          </div>)
      
    )


  )
}
     
    </div>
  )
}
export async function getServerSideProps(){
  
  const res=await fetch('https://jsonplaceholder.typicode.com/todos?_limit=20')
  const data=await res.json()
  return {
    props:{todos:data}
  }
  
  }