import Head from "next/head";
import { dehydrate, QueryClient, useQuery } from "react-query";
import styles from "../styles/Home.module.css";

const getPosts = async () =>
  await (
    await fetch("https://jsonplaceholder.typicode.com/posts?_limit=20")
  ).json();
export default function Home({ posts }) {
  const { data, isLoading, isFetching } = useQuery("posts", getPosts);
  console.log(data);
  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>No data!</div>;
  return (
    <div className={styles.container}>
      <Head>
        <title>SSR demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {data.map((post) => (
          <div
            style={{
              display: "flex",
              alignItems: "center",
              textAlign: "center",
            }}
            key={`post${post.id}`}
          >
            <span>Post #{post.id} :</span>
            <h3 style={{ marginLeft: "30px" }}>{post.title}</h3>
          </div>
        ))}
      </div>
    </div>
  );
}
 export async function getStaticProps(){
   const queryClient=new QueryClient()
  await queryClient.prefetchQuery("posts",getPosts)
   return {
 props: {
       dehydratedState: dehydrate(queryClient)
}
   }

   }
